// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sereallctpcqrdjmvwrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcmVhbGxjdHBjcXJkam12d3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDE5NTUsImV4cCI6MjA2OTkxNzk1NX0.RlE-LfVjcIGbWJztzUYoAx9fCAxeFCgjZTtrGSvWZsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});